apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: booking-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          envFrom:
            - configMapRef:
                name: parkirinaja-config
            - secretRef:
                name: parkirinaja-secret
          env:
            - name: PORT
              value: "3003"
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-db:5432/$(POSTGRES_DB)
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec:
  selector:
    app: booking-service
  ports:
    - name: http
      port: 3003
      targetPort: 3003
  type: ClusterIP